language: java

jdk:
  - openjdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
  - gradle assemble

branches:
  only:
    - develop

after_success:
  - ./gradlew jacocoTestReport coveralls
