version: '3.1'

services:
  database:
    image: postgres
    container_name: kot-database
    networks:
      - local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yan123
  wiremock:
    container_name: kot-mocks
    image: wiremock/wiremock
    networks:
      - local
    ports:
      - "36003:8080"
    volumes:
      - ./ci/stubs:/home/wiremock

networks:
  local:
    driver: bridge
