version: '3.1'

services:
  database:
    image: postgres
    container_name: kot-database
    ports:
      - "5434:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yan123
  wiremock:
    container_name: kot-mocks
    image: rodolpheche/wiremock:2.26.3-alpine
    ports:
      - "5001:8080"
    volumes:
      - ./ci/stubs:/home/wiremock